---
title: "M4M"
subtitle: "Welcome to the Metadata for Machines resource page"
---

(Robot_logos_2.png)

Metadata for Machines (M4M) workshops are agile, hackathon-style events that bring together domain experts (who are able and willing to represent a domain community) with FAIR metadata experts (data stewards) who guide a discussion leading to the metadata requirements that meet the FAIR data needs of that domain community. M4M Workshops are lightweight, fast-track (often 1-day) events where policy and domain experts can build new, or make informed choices regarding the reuse of already existing metadata schema. Although M4M Workshops can serve many purposes, they are usually intended to kick-start FAIRification efforts with minimally viable metadata components that are modular, and can be later extended as needed.

M4M Worskhops have two objectives:

First, most M4M Workshops focus on a simple but extensible conceptual model and RDF schema that solve clearly identified FAIR-related metadata goals for that domain. Based on numerous considerations, the metadata expert will recommend if a new schema should be created or if an existing schema can be efficiently repurposed. In most cases, it is also possible to employ metadata modeling tools to build reusable metadata templates following that schema providing user-friendly interfaces and input forms. This will later allow domain experts who may not have technical skills, to nonetheless create metadata instances without expert supervision.
The second objective of a M4M Workshop is the deposition of the defined metadata schema/template into a FAIR repository, where they can be easily found and reused by other communities that often have similar metadata requirements. The overall goal of a M4M Workshop is a public Declaration by the domain community to the use and reuse of particular FAIR metadata schema/templates. This declaration could take the form of a FAIR Implementation Profile or a statement in a Data Management Plan.
