project:
  type: website

website:
  title: "GO FAIR Wiki"
  repo-url: "https://github.com/gofair-foundation/gofair-wiki"
  repo-actions: [edit, issue]
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: News
        href: docs/news/index.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



