project:
  type: website
  output-dir: _site

website:
  title: "GO FAIR Wiki"
  repo-url: "https://github.com/gofair-foundation/gofair-wiki"
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  page-footer:
    left: |
        [GO FAIR Foundation](https://www.gofair.foundation/)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
  announcement: 
    content: "This website is under construction"
    position: below-navbar
  navbar:
    background: light
    title: false
    search: true
    left:
      
      - text: Overview
        href: index.qmd
      - text: "Guide"
        href: docs/guide/index.qmd
      - text: News
        href: docs/news/index.qmd

execute:
  freeze: auto
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


