project:
  type: website
  output-dir: _site

website:
  title: "GO FAIR Wiki"
  image: docs/img/GGF_checkmark.png
  repo-url: "https://github.com/gofair-foundation/gofair-wiki"
  repo-actions: [edit, issue]
  page-navigation: true
  
#  bread-crumbs: true
#
#
  
#  page-footer:
#    left: |
#        [GO FAIR Foundation](https://www.gofair.foundation/)
#    center:
#

#  announcement: 
#    content: "This website is under construction"
#    position: below-navbar
#

  navbar:
    background: light
    title: false
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Guide
        href: docs/guide/index.qmd
      - text: News
        href: docs/news/index.qmd
      - text: FAIR Connect
        href: docs/fair-connect/fair-connect.qmd
      - text: Contributing
        href: contributing.qmd
      - text: License
        href: license.qmd
        
  sidebar:
    - id: guide
      collapse-level: 1
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd
          contents:
          - section: "FIP Wizard User Guide"
            contents:
              - docs/fip/background.qmd
              - docs/fip/overview.qmd
              - docs/fip/getting-started.qmd
              - docs/fip/completing-questionnaire.qmd
              - docs/fip/minting-nanopublications.qmd
              - docs/fip/publishing.qmd
              - docs/fip/revising.qmd
          - section: "Nanopublications"
            contents:
              - docs/np/index.qmd
          - section: "SIP Wizard User Guide"
            contents:
              - docs/sip/content.qmd
    - id: fair-connect
      collapse-level: 1
      contents:
      - section: "FAIR Connect"
        href: docs/fair-connect/fair-connect.md
            
execute:
  freeze: auto
  
bibliography: references.bib
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


