project:
  type: website
  output-dir: _site

website:
  title: "GO FAIR Wiki"
  image: docs/img/GGF_checkmark.png
  site-url: "https://wiki.gofair.foundation/"
  repo-url: "https://github.com/gofair-foundation/gofair-wiki"
  repo-actions: [edit, issue]
  page-navigation: true
  
#  bread-crumbs: true
#
#
  
  page-footer:
        left:
          - text: License
          - href: license.qmd
  

#  announcement: 
#    content: "This website is under construction"
#    position: below-navbar
#

  navbar:
    background: light
    title: false
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: FIP
        href: /fip
      - text: Guide
        href: docs/guide/index.qmd
      - text: News
        href: docs/news/index.qmd
      - text: FAIR Connect
        href: docs/fair-connect/fair-connect.qmd
      - text: Contributing
        href: contributing.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: github
        href: https://github.com/gofair-foundation/gofair-wiki
        text: GFF Wiki GitHub
      - icon: rss
        href: https://wiki.gofair.foundation/docs/news/index.xml
        text: GFF News RSS
  
  sidebar:
    - id: guide
      collapse-level: 1
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd
          contents:
          - section: "FIP Wizard User Guide"
            contents:
              - docs/fip/content.qmd
          - section: "Nanopublications"
            contents:
              - docs/np/index.qmd
          - section: "SIP Wizard User Guide"
            contents:
              - docs/sip/content.qmd
          - section: "Authors and Contributors"
            contents:
              - docs/guide/authors.qmd
    - id: fair-connect
      collapse-level: 1
      contents:
      - section: "FAIR Connect"
        href: docs/fair-connect/fair-connect.md
            
execute:
  freeze: auto
  
bibliography: references.bib
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

include-after-body:
  - text: |
      <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
      </script>
